# Generated by Django 2.2.14 on 2021-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
